version: "3.7"
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=True
  - AIRFLOW__CORE__LOAD_EXAMPLES=True
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/db/airflow.db
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
  - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
  - FERNET_KEY=My_Secret_Key
x-airflow-image: &airflow_image apache/airflow:2.0.0-python3.8

services:
  init:
    image: *airflow_image
    volumes:
      - ./db:/opt/airflow/db
      - ./logs:/opt/airflow/logs
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  scheduler:
    image: *airflow_image
    depends_on:
    - init
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./db:/opt/airflow/db
      - ./logs:/opt/airflow/logs
    environment: *airflow_environment
    command: scheduler

  webserver:
    image: *airflow_image
    depends_on:
    - init
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./db:/opt/airflow/db
      - ./logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver
